apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: microfrontends.operator.example.ru
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: operator.example.ru
  # list of versions supported by this CustomResourceDefinition
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: microfrontends
    # singular name to be used as an alias on the CLI and for display
    singular: microfrontend
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Microfrontend
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                path:
                  type: string
                url:
                  type: string
                filename:
                  type: string
                scope:
                  type: string
                module:
                  type: string
                widgets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      module:
                        type: string
            status:
              type: object
              properties:
                status:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: State
          type: string
          jsonPath: .status.status