apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.ru.example.operator.targetService.configMap.name }}-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.ru.example.operator.targetService.configMap.name }}-updater
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Values.ru.example.operator.targetService.namespace }}