image:
  image: gateway-k8s-operator
  build: pre-ci
  pullPolicy: IfNotPresent

ru:
  example:
    javaOptions: "-Duser.timezone=Europe/Moscow -XX:+UseG1GC -XX:+UseStringDeduplication"
    operator:
      watchedCr:
        label:
          name: "app.example.ru/name"
          value: "gateway"
      watchedNamespaces:
        label:
          name: "operator.example.ru/name"
          value: "gateway-k8s-operator"
        refresh:
          initialDelay: PT1M
          delay: PT30S
      targetService:
        namespace: "local-ns"
        port: 8080
        pod:
          label:
            name: "app.kubernetes.io/instance"
            value: "gateway"
          refresh:
            delay: PT90S
        configMap:
          name: "gateway-config"
          refresh:
            initialDelay: PT1M
            delay: PT30S

health:
  failureThreshold: 3

imagePullSecrets: [ {name: "regcred"} ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
